# Generated by Django 6.1.1 on 2026-09-13 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رویداد امنیتی',
                'verbose_name_plural': 'گزارش رویدادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان وام')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ کل وام (تومان)')),
                ('monthly_payment', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='قسط ماهانه هر عضو (تومان)')),
                ('service_fee', models.DecimalField(decimal_places=0, default=0, help_text='هزینهٔ اداره صندوق، نه سود/بهره — این صندوق قرض\u200cالحسنه (بدون سود) است.', max_digits=14, verbose_name='هزینهٔ خدمات صندوق (تومان)')),
                ('duration_months', models.PositiveIntegerField(help_text='هم تعداد اقساط و هم تعداد قرعه\u200cکشی\u200cهای این طرح.', verbose_name='تعداد دوره / ماه')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت (حداکثر تعداد عضو)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس (هنوز نمایش داده نمی\u200cشود)'), ('open', 'باز برای رزرو'), ('full', 'تکمیل ظرفیت'), ('in_progress', 'در حال اجرا'), ('completed', 'پایان\u200cیافته'), ('cancelled', 'لغوشده')], default='open', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL, verbose_name='ایجادشده توسط')),
            ],
            options={
                'verbose_name': 'طرح وام',
                'verbose_name_plural': 'طرح\u200cهای وام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'تأییدشده'), ('cancelled', 'لغوشده')], default='confirmed', max_length=20)),
                ('has_won', models.BooleanField(default=False, verbose_name='برندهٔ قرعه\u200cکشی شده')),
                ('won_round', models.PositiveIntegerField(blank=True, null=True, verbose_name='دورهٔ برد')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('loan_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='loans.loanplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='شمارهٔ دوره')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='مبلغ (تومان)')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='سررسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق')], default='pending', max_length=20)),
                ('gateway', models.CharField(blank=True, max_length=30)),
                ('gateway_authority', models.CharField(blank=True, db_index=True, max_length=100)),
                ('gateway_ref', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL, verbose_name='تأییدشده توسط (تأیید دستی)')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.reservation')),
            ],
            options={
                'verbose_name': 'قسط',
                'verbose_name_plural': 'اقساط',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='LotteryDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(verbose_name='شمارهٔ دوره')),
                ('scheduled_at', models.DateTimeField(verbose_name='زمان اعلام\u200cشدهٔ قرعه\u200cکشی')),
                ('status', models.CharField(choices=[('scheduled', 'زمان\u200cبندی\u200cشده'), ('completed', 'برگزارشده'), ('cancelled', 'لغوشده')], default='scheduled', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('eligible_snapshot', models.TextField(blank=True, help_text='فهرست رزروهای واجدشرایط در لحظهٔ قرعه\u200cکشی (برای رسیدگی به اعتراض)')),
                ('integrity_hash', models.CharField(blank=True, help_text='اثر انگشت SHA-256 برای اثبات عدم دستکاری بعدی', max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_draws', to=settings.AUTH_USER_MODEL)),
                ('loan_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottery_draws', to='loans.loanplan')),
                ('winner_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='loans.reservation', verbose_name='رزروِ برنده')),
            ],
            options={
                'verbose_name': 'قرعه\u200cکشی',
                'verbose_name_plural': 'قرعه\u200cکشی\u200cها',
                'ordering': ['round_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(fields=('user', 'loan_plan'), name='uq_user_plan'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('reservation', 'round_number'), name='uq_reservation_round'),
        ),
        migrations.AddConstraint(
            model_name='lotterydraw',
            constraint=models.UniqueConstraint(fields=('loan_plan', 'round_number'), name='uq_plan_round'),
        ),
    ]
