# Generated by Django 5.2.17 on 2026-09-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_payment_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payout_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که مدیر، واریز مبلغ وام به حساب برنده را تأیید می\u200cکند.', null=True, verbose_name='تأیید واریز وام توسط مدیر'),
        ),
    ]
